name: pinball-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit=11.8 #GPU
  - opencv
  - matplotlib
  - pip
  - pip:
      - tqdm