name: pinball
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - opencv
  - matplotlib
  - pip
  - pip:
      - tqdm
      - absl-py==2.2.2
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - black==25.1.0
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - filelock==3.13.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.24.0
      - gradio-client==1.8.0
      - groovy==0.1.2
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - iopath==0.1.9
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - networkx==3.3
      - omegaconf==2.3.0
      - orjson==3.10.16
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.7
      - portalocker==3.1.1
      - protobuf==4.25.3
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.8
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - ruff==0.11.5
      - safehttpx==0.1.6
      - scipy==1.15.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.0.1
      - tomlkit==0.13.2
      - triton==3.2.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - ultralytics==8.3.106
      - ultralytics-thop==2.0.14
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - yacs==0.1.8
